### ISSUE TITLE
Crash when the offhand interacts with Sugar Block from CandyCraft mod

### ISSUE THREAD

**Issue by huihiuhuai** [GTNewHorizons/Backhand#19] opened 2024-07-27 06:55 UTC
[crash-2024-07-27_14.41.52-client.txt](https://github.com/user-attachments/files/16398482/crash-2024-07-27_14.41.52-client.txt)

Sugar Block is the portal frame block for CandyCraft (similar to obsidian). Crash may be related to insufficient null checking in CandyCraft's code.

**Comment by Lyfts** [comment] 2024-07-31 07:01
I can confirm that it's due to an incorrect null check. It's probably gonna get fixed in Hodgepodge as the crash isn't caused or related to this mod.

**Closed** 2024-07-31 10:41 UTC
