### ISSUE TITLE
Crash when switching the patterns of carpenter's bed with offhand

### ISSUE THREAD

**Issue by huihiuhuai** [GTNewHorizons/Backhand#22] opened 2024-08-02 06:27 UTC
https://pastebin.com/pBJxtW2C

**Comment by Lyfts** [comment] 2024-08-02 14:18
I can't reproduce. Can you check if it still happens with https://github.com/GTNewHorizons/Backhand/releases/tag/1.5.7-pre?

**Comment by huihiuhuai** [comment] 2024-08-02 15:35
I also happens with 1.5.7.

**Comment by Lyfts** [comment] 2024-08-02 16:01
Which block are you using it on and can you send a new log?

**Comment by huihiuhuai** [comment] 2024-08-02 16:10
ohhh i was using hammer right click on carpenters bed to switch colors

**Comment by huihiuhuai** [comment] 2024-08-03 11:05
cant reproduce in 1.5.8-pre

**Comment by huihiuhuai** [comment] 2024-08-04 04:03
https://github.com/user-attachments/assets/b060e372-826c-4115-80e9-454b437c1093

Crash with Carpenter's garage door.
https://pastebin.com/QLuAZK1K

**Comment by Lyfts** [comment] 2024-08-04 16:22
That is hopefully be fixed in https://github.com/GTNewHorizons/Backhand/releases/tag/1.5.10-pre

**Comment by huihiuhuai** [comment] 2024-08-05 05:30
[crash-2024-08-05_13.28.44-client.txt](https://github.com/user-attachments/files/16491106/crash-2024-08-05_13.28.44-client.txt)
1.5.10-pre

**Comment by Lyfts** [comment] 2024-08-05 14:44
Third times the charm https://github.com/GTNewHorizons/Backhand/releases/tag/1.5.11-pre this time it should definitely be fixed. 
You'll need to install https://github.com/GTNewHorizons/GTNHLib/releases if you don't already have it.

**Closed** 2024-08-11 08:55 UTC
