### ISSUE TITLE
Cannot use Chest Transporter to pick up chests when offhand is holding an item 

### ISSUE THREAD

**Issue by huihiuhuai** [GTNewHorizons/Backhand#24] opened 2024-08-02 15:46 UTC

**Comment by huihiuhuai** [comment] 2024-08-02 16:11
Chest Transporter

**Comment by Lyfts** [comment] 2024-08-02 17:36
Are you using it on a vanilla chest or some modded chest?

**Comment by huihiuhuai** [comment] 2024-08-02 23:17
Vanilla chest. There was torch or enchanted book in the offhand.

**Comment by Lyfts** [comment] 2024-08-02 23:31
![bh_chest_transporter](https://github.com/user-attachments/assets/9fd0bc91-606e-4c14-9ec9-92d44a71863c)
It seems to be fixed by one of the later commits, I'll' make a new pre version some time tomorrow.

**Comment by Lyfts** [comment] 2024-08-03 09:09
Try with https://github.com/GTNewHorizons/Backhand/releases/tag/1.5.8-pre

**Comment by Darek505** [comment] 2024-08-03 18:49
(1.5.9-pre) I can confirm that the chest can be taken, but it is no possible to place it when there is another item in the offhand:

<details>

<summary></summary>

https://github.com/user-attachments/assets/10b68707-c2b3-4d05-89e1-9e0ca9c07446


</details>

**Comment by Lyfts** [comment] 2024-08-03 18:56
Yep the chest transporter uses an event to place the chest rather than `onItemUse` or `onItemUseFirst,` which means that we would have to implement explicit support for that.

**Closed** 2024-08-29 08:59 UTC
